# Note(ethanjli): This CI workflow is a temporary measure to automatically synchronize the
# docs-staging & docs-prod repos with the master branch of the docs repo, so that @beniroquai can
# deploy all changes directly to staging & production. Once we stabilize our staging & prod
# deployments, we should delete this CI workflow!
---
name: release channel (dev)
on:
  push:
    branches:
      - 'master'
      - 'main'
      - 'edge'

jobs:
  ff-branch-staging:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: |
          git checkout staging
          git merge --ff-only ${{ github.ref_name }}

      - uses: ad-m/github-push-action@v0.8.0
        with:
          branch: staging

  deploy-repo-staging:
    # We call this workflow manually because it doesn't appear to be triggered automatically by a
    # push of the dev branch from the ff-branch job:
    uses: ./.github/workflows/deploy-staging.yml
    needs: ff-branch-staging
    secrets: inherit

  ff-branch-prod:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: |
          git checkout prod
          git merge --ff-only ${{ github.ref_name }}

      - uses: ad-m/github-push-action@v0.8.0
        with:
          branch: prod

  deploy-repo-prod:
    # We call this workflow manually because it doesn't appear to be triggered automatically by a
    # push of the dev branch from the ff-branch job:
    uses: ./.github/workflows/deploy-prod.yml
    needs: ff-branch-prod
    secrets: inherit
