name: sync repo (prod)

on:
  push:
    branches:
      - 'prod'
  workflow_call:
  workflow_dispatch:

env:
  REPO: ${{ vars.REPO }}

defaults:
  run:
    shell: bash

jobs:
  deploy:
    environment:
      name: repo-prod
      url: https://github.com/${{ env.REPO }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: prod

      - name: Add remote repo ${{ env.REPO }}
        run: |
          mkdir -p "$HOME/.ssh"
          echo "${{ secrets.SSH_DEPLOY_KEY }}" > "$HOME/.ssh/deploy_key"
          chmod 600 "$HOME/.ssh/deploy_key"

          export GIT_SSH_COMMAND="ssh -i $HOME/.ssh/deploy_key"
          git remote add prod-repo git@github.com:${{ env.REPO }}.git
          git fetch --all

      - name: Fast-forward deployment branch
        run: |
          git checkout -b deploy --track prod-repo/deploy
          git merge --ff-only prod

      - name: Push to remote repo
        run: |
          export GIT_SSH_COMMAND="ssh -i $HOME/.ssh/deploy_key"
          git push
